- name: allplaybook
  hosts: all
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  vars:
      - administrator_name: corpadmin
  tasks:
      - name: Install updates
        yum: name=* state=latest

      - name: Create user
        user:
          name: "{{ administrator_name }}"
          password: kfvkf

- name: nginxupdate
  hosts: web1
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  tasks:
      - name: Updating nginx
        yum: name=nginx state=present
        debugger: on_skipped
      - name: Copy template
        template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

      - name: Running nginx
        service: name=nginx state=started enabled=yes

- name: mysqlupdate
  hosts: database1
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  become: yes
  tasks:
      - name: Updating mysql
        yum: name=mysql-server state=present

      - name: Configure mysql
        service: name=mysqld state=started enabled=yes

      - name: Looping directories
        file: dest=/var/data/client{{ item }} state=directory
        with_sequence: start=1 end=5 stride=1
